name: Build PyctureConverter

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: pyinstaller --name PyctureConverter-Windows --noconsole --onefile --add-data "assets;assets" src/main.py

    - name: Build for Mac/Linux
      if: matrix.os != 'windows-latest'
      run: pyinstaller --name PyctureConverter-${{ matrix.os }} --noconsole --onefile --add-data "assets:assets" src/main.py

    - name: Upload Finished App
      uses: actions/upload-artifact@v4
      with:
        name: PyctureConverter-${{ matrix.os }}
        path: dist/*